data:
  target: 'loan_status'
  numerical_features: ['person_age', 'person_income', 'person_emp_exp', 'loan_amnt', 'loan_int_rate', 'loan_percent_income', 'cb_person_cred_hist_length', 'credit_score']

model:
  features: ["person_income", "loan_amnt", "loan_int_rate", "previous_loan_defaults_on_file_Yes", "person_home_ownership_OWN"]



